### ISSUE TITLE
Unable to download the WikiText-103 dataset

### ISSUE THREAD

**Issue by Iust1n2** [mega002/ffn-layers#1]
I'm getting an acces denied error when i try to download the dataset from this [link](https://blog.salesforceairesearch.com/the-wikitext-long-term-dependency-language-modeling-dataset/).

Also, the link from [here](https://github.com/mega002/ff-layers/blob/main/examples/language_model/README.md#1-preprocess-the-data) is invalid too.

**Comment by mega002** [comment]
Hi @Iust1n2 ,

Thanks for creating this issue.

Yes, I get this error as well. I am not sure why they restricted the download from the website.
In any case, I believe the same data is available on HuggingFace:
https://huggingface.co/datasets/Salesforce/wikitext

I hope this helps. Will close this issue for now as I am not able to maintain the code in this repository anymore, and specifically validate that the results are reproducible with the data on HuggingFace.

Best,
Mor
